<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>com.github.darmuh.AddControls</AssemblyName>
    <AssemblyTitle>AddControls</AssemblyTitle>
    <Version>0.2.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Unity.InputSystem">
      <HintPath>..\..\unityref\Unity.InputSystem.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
